[tools]
python = "3.11"
rust = "latest"
uv = "latest"

[tasks.comp]
run = [
    "gcc -Wall -fopenmp {{arg(name='fname')}} -o {{arg(name='fname')}}.out",
    "./{{arg(name='fname')}}.out {{option(name='arg', default='')}}"
]
dir = "{{cwd}}"

[tasks.c]
run = [
    "gcc -Wall {{arg(name='fname')}} -o {{arg(name='fname')}}.out",
    "./{{arg(name='fname')}}.out {{option(name='arg', default='')}}"
]
dir = "{{cwd}}"

[tasks.gituseriniad]
run = [
    "git config user.name 's1f10230101'",
    "git config user.email 's1f102301011@iniad.org'"
    ]
dir = "{{cwd}}"

[tasks.gituserhiroki]
run = [
    "git config user.name 'hiroki706'",
    "git config user.email 'hiroki.okubo.tokyo@gmail.com'"
    ]
dir = "{{cwd}}"
