data = """(0.001) SELECT "albums"."AlbumId", "albums"."Title", "albums"."ArtistId" FROM "albums"; args=(); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 1 LIMIT 21; args=(1,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 2 LIMIT 21; args=(2,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 2 LIMIT 21; args=(2,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 1 LIMIT 21; args=(1,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 3 LIMIT 21; args=(3,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 4 LIMIT 21; args=(4,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 5 LIMIT 21; args=(5,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 6 LIMIT 21; args=(6,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 7 LIMIT 21; args=(7,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 8 LIMIT 21; args=(8,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 8 LIMIT 21; args=(8,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 9 LIMIT 21; args=(9,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 10 LIMIT 21; args=(10,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 11 LIMIT 21; args=(11,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 11 LIMIT 21; args=(11,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 12 LIMIT 21; args=(12,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 12 LIMIT 21; args=(12,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 13 LIMIT 21; args=(13,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 14 LIMIT 21; args=(14,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 15 LIMIT 21; args=(15,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 16 LIMIT 21; args=(16,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 16 LIMIT 21; args=(16,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 17 LIMIT 21; args=(17,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 18 LIMIT 21; args=(18,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 18 LIMIT 21; args=(18,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 19 LIMIT 21; args=(19,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 19 LIMIT 21; args=(19,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 20 LIMIT 21; args=(20,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 21 LIMIT 21; args=(21,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 22 LIMIT 21; args=(22,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 23 LIMIT 21; args=(23,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 21 LIMIT 21; args=(21,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 24 LIMIT 21; args=(24,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 6 LIMIT 21; args=(6,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 50 LIMIT 21; args=(50,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 51 LIMIT 21; args=(51,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 52 LIMIT 21; args=(52,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 53 LIMIT 21; args=(53,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 54 LIMIT 21; args=(54,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 55 LIMIT 21; args=(55,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 56 LIMIT 21; args=(56,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 57 LIMIT 21; args=(57,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 58 LIMIT 21; args=(58,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 22 LIMIT 21; args=(22,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 21 LIMIT 21; args=(21,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 59 LIMIT 21; args=(59,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 37 LIMIT 21; args=(37,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 68 LIMIT 21; args=(68,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 68 LIMIT 21; args=(68,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 58 LIMIT 21; args=(58,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 69 LIMIT 21; args=(69,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 70 LIMIT 21; args=(70,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 21 LIMIT 21; args=(21,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 76 LIMIT 21; args=(76,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 76 LIMIT 21; args=(76,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 77 LIMIT 21; args=(77,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 77 LIMIT 21; args=(77,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 58 LIMIT 21; args=(58,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 58 LIMIT 21; args=(58,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 58 LIMIT 21; args=(58,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 58 LIMIT 21; args=(58,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 58 LIMIT 21; args=(58,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 58 LIMIT 21; args=(58,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 58 LIMIT 21; args=(58,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 58 LIMIT 21; args=(58,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 58 LIMIT 21; args=(58,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 78 LIMIT 21; args=(78,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 79 LIMIT 21; args=(79,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 80 LIMIT 21; args=(80,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 80 LIMIT 21; args=(80,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 41 LIMIT 21; args=(41,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 81 LIMIT 21; args=(81,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 81 LIMIT 21; args=(81,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 82 LIMIT 21; args=(82,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 82 LIMIT 21; args=(82,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 82 LIMIT 21; args=(82,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 82 LIMIT 21; args=(82,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 83 LIMIT 21; args=(83,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 84 LIMIT 21; args=(84,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 84 LIMIT 21; args=(84,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 84 LIMIT 21; args=(84,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 84 LIMIT 21; args=(84,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 85 LIMIT 21; args=(85,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 86 LIMIT 21; args=(86,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 27 LIMIT 21; args=(27,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 27 LIMIT 21; args=(27,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 27 LIMIT 21; args=(27,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 87 LIMIT 21; args=(87,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 54 LIMIT 21; args=(54,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 88 LIMIT 21; args=(88,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 88 LIMIT 21; args=(88,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 88 LIMIT 21; args=(88,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 89 LIMIT 21; args=(89,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 90 LIMIT 21; args=(90,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 91 LIMIT 21; args=(91,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 92 LIMIT 21; args=(92,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 92 LIMIT 21; args=(92,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 92 LIMIT 21; args=(92,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 93 LIMIT 21; args=(93,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 94 LIMIT 21; args=(94,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 95 LIMIT 21; args=(95,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 46 LIMIT 21; args=(46,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 96 LIMIT 21; args=(96,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 97 LIMIT 21; args=(97,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 98 LIMIT 21; args=(98,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 52 LIMIT 21; args=(52,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 22 LIMIT 21; args=(22,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 22 LIMIT 21; args=(22,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 22 LIMIT 21; args=(22,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 22 LIMIT 21; args=(22,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 22 LIMIT 21; args=(22,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 22 LIMIT 21; args=(22,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 22 LIMIT 21; args=(22,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 22 LIMIT 21; args=(22,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 22 LIMIT 21; args=(22,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 22 LIMIT 21; args=(22,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 22 LIMIT 21; args=(22,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 22 LIMIT 21; args=(22,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 99 LIMIT 21; args=(99,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 99 LIMIT 21; args=(99,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 100 LIMIT 21; args=(100,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 101 LIMIT 21; args=(101,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 101 LIMIT 21; args=(101,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 102 LIMIT 21; args=(102,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 103 LIMIT 21; args=(103,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 104 LIMIT 21; args=(104,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 105 LIMIT 21; args=(105,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 50 LIMIT 21; args=(50,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 50 LIMIT 21; args=(50,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 50 LIMIT 21; args=(50,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 50 LIMIT 21; args=(50,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 50 LIMIT 21; args=(50,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 50 LIMIT 21; args=(50,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 50 LIMIT 21; args=(50,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 50 LIMIT 21; args=(50,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 50 LIMIT 21; args=(50,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 68 LIMIT 21; args=(68,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 42 LIMIT 21; args=(42,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 42 LIMIT 21; args=(42,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 106 LIMIT 21; args=(106,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 108 LIMIT 21; args=(108,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 109 LIMIT 21; args=(109,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 110 LIMIT 21; args=(110,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 110 LIMIT 21; args=(110,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 111 LIMIT 21; args=(111,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 112 LIMIT 21; args=(112,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 113 LIMIT 21; args=(113,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 113 LIMIT 21; args=(113,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 113 LIMIT 21; args=(113,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 114 LIMIT 21; args=(114,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 114 LIMIT 21; args=(114,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 114 LIMIT 21; args=(114,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 114 LIMIT 21; args=(114,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 114 LIMIT 21; args=(114,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 115 LIMIT 21; args=(115,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 116 LIMIT 21; args=(116,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 117 LIMIT 21; args=(117,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 118 LIMIT 21; args=(118,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 118 LIMIT 21; args=(118,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 118 LIMIT 21; args=(118,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 118 LIMIT 21; args=(118,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 118 LIMIT 21; args=(118,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 120 LIMIT 21; args=(120,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 121 LIMIT 21; args=(121,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 51 LIMIT 21; args=(51,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 51 LIMIT 21; args=(51,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 122 LIMIT 21; args=(122,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 124 LIMIT 21; args=(124,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 124 LIMIT 21; args=(124,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 124 LIMIT 21; args=(124,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 125 LIMIT 21; args=(125,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 126 LIMIT 21; args=(126,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 127 LIMIT 21; args=(127,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 127 LIMIT 21; args=(127,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 127 LIMIT 21; args=(127,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 128 LIMIT 21; args=(128,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 59 LIMIT 21; args=(59,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 59 LIMIT 21; args=(59,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 130 LIMIT 21; args=(130,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 130 LIMIT 21; args=(130,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 131 LIMIT 21; args=(131,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 131 LIMIT 21; args=(131,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 132 LIMIT 21; args=(132,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 53 LIMIT 21; args=(53,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 133 LIMIT 21; args=(133,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 134 LIMIT 21; args=(134,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 135 LIMIT 21; args=(135,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 136 LIMIT 21; args=(136,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 137 LIMIT 21; args=(137,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 137 LIMIT 21; args=(137,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 138 LIMIT 21; args=(138,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 139 LIMIT 21; args=(139,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 139 LIMIT 21; args=(139,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 140 LIMIT 21; args=(140,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 141 LIMIT 21; args=(141,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 142 LIMIT 21; args=(142,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 142 LIMIT 21; args=(142,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 142 LIMIT 21; args=(142,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 143 LIMIT 21; args=(143,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 143 LIMIT 21; args=(143,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 144 LIMIT 21; args=(144,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 145 LIMIT 21; args=(145,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 145 LIMIT 21; args=(145,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 146 LIMIT 21; args=(146,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 146 LIMIT 21; args=(146,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 147 LIMIT 21; args=(147,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 147 LIMIT 21; args=(147,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 148 LIMIT 21; args=(148,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 149 LIMIT 21; args=(149,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 149 LIMIT 21; args=(149,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 149 LIMIT 21; args=(149,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 150 LIMIT 21; args=(150,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 150 LIMIT 21; args=(150,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 150 LIMIT 21; args=(150,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 150 LIMIT 21; args=(150,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 150 LIMIT 21; args=(150,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 150 LIMIT 21; args=(150,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 150 LIMIT 21; args=(150,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 150 LIMIT 21; args=(150,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 150 LIMIT 21; args=(150,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 151 LIMIT 21; args=(151,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 152 LIMIT 21; args=(152,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 152 LIMIT 21; args=(152,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 152 LIMIT 21; args=(152,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 152 LIMIT 21; args=(152,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 153 LIMIT 21; args=(153,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 72 LIMIT 21; args=(72,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 155 LIMIT 21; args=(155,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 156 LIMIT 21; args=(156,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 156 LIMIT 21; args=(156,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 156 LIMIT 21; args=(156,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 157 LIMIT 21; args=(157,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 158 LIMIT 21; args=(158,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 159 LIMIT 21; args=(159,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 150 LIMIT 21; args=(150,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 114 LIMIT 21; args=(114,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 179 LIMIT 21; args=(179,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 180 LIMIT 21; args=(180,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 36 LIMIT 21; args=(36,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 196 LIMIT 21; args=(196,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 149 LIMIT 21; args=(149,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 197 LIMIT 21; args=(197,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 198 LIMIT 21; args=(198,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 199 LIMIT 21; args=(199,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 200 LIMIT 21; args=(200,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 201 LIMIT 21; args=(201,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 202 LIMIT 21; args=(202,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 203 LIMIT 21; args=(203,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 204 LIMIT 21; args=(204,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 205 LIMIT 21; args=(205,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 8 LIMIT 21; args=(8,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 206 LIMIT 21; args=(206,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 207 LIMIT 21; args=(207,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 208 LIMIT 21; args=(208,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 209 LIMIT 21; args=(209,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 210 LIMIT 21; args=(210,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 211 LIMIT 21; args=(211,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 212 LIMIT 21; args=(212,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 213 LIMIT 21; args=(213,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 214 LIMIT 21; args=(214,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 215 LIMIT 21; args=(215,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 216 LIMIT 21; args=(216,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 217 LIMIT 21; args=(217,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 218 LIMIT 21; args=(218,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 219 LIMIT 21; args=(219,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 220 LIMIT 21; args=(220,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 221 LIMIT 21; args=(221,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 222 LIMIT 21; args=(222,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 223 LIMIT 21; args=(223,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 224 LIMIT 21; args=(224,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 225 LIMIT 21; args=(225,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 226 LIMIT 21; args=(226,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 227 LIMIT 21; args=(227,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 228 LIMIT 21; args=(228,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 229 LIMIT 21; args=(229,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 230 LIMIT 21; args=(230,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 231 LIMIT 21; args=(231,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 232 LIMIT 21; args=(232,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 233 LIMIT 21; args=(233,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 234 LIMIT 21; args=(234,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 235 LIMIT 21; args=(235,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 236 LIMIT 21; args=(236,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 237 LIMIT 21; args=(237,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 238 LIMIT 21; args=(238,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 240 LIMIT 21; args=(240,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 241 LIMIT 21; args=(241,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 242 LIMIT 21; args=(242,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 243 LIMIT 21; args=(243,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 244 LIMIT 21; args=(244,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 245 LIMIT 21; args=(245,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 226 LIMIT 21; args=(226,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 245 LIMIT 21; args=(245,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 246 LIMIT 21; args=(246,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 247 LIMIT 21; args=(247,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 208 LIMIT 21; args=(208,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 248 LIMIT 21; args=(248,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 249 LIMIT 21; args=(249,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 250 LIMIT 21; args=(250,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 251 LIMIT 21; args=(251,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 248 LIMIT 21; args=(248,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 252 LIMIT 21; args=(252,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 252 LIMIT 21; args=(252,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 253 LIMIT 21; args=(253,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 254 LIMIT 21; args=(254,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 255 LIMIT 21; args=(255,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 256 LIMIT 21; args=(256,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 257 LIMIT 21; args=(257,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 258 LIMIT 21; args=(258,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 259 LIMIT 21; args=(259,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 260 LIMIT 21; args=(260,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 261 LIMIT 21; args=(261,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 262 LIMIT 21; args=(262,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 263 LIMIT 21; args=(263,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 264 LIMIT 21; args=(264,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 265 LIMIT 21; args=(265,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 248 LIMIT 21; args=(248,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 266 LIMIT 21; args=(266,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 267 LIMIT 21; args=(267,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 268 LIMIT 21; args=(268,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 269 LIMIT 21; args=(269,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 270 LIMIT 21; args=(270,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 271 LIMIT 21; args=(271,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 226 LIMIT 21; args=(226,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 272 LIMIT 21; args=(272,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 273 LIMIT 21; args=(273,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 274 LIMIT 21; args=(274,); alias=default
(0.000) SELECT "artists"."ArtistId", "artists"."Name" FROM "artists" WHERE "artists"."ArtistId" = 275 LIMIT 21; args=(275,); alias=default"""

[print(s[7:-13], sep="\n") for s in data.split("\n")]
